/**
 * Mock data for the charging station maintenance system
 * @module mockData
 */

export const mockGroups = [
  {
    id: "G001",
    name: "Bangkok North Team",
    description: "Maintenance team for northern Bangkok area",
    tags: ["bangkok", "north", "team-a"],
    status: "active",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "G002",
    name: "Bangkok South Team",
    description: "Maintenance team for southern Bangkok area",
    tags: ["bangkok", "south", "team-b"],
    status: "active",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "G003",
    name: "Emergency Response Team",
    description: "Rapid response unit for critical issues",
    tags: ["emergency", "priority", "critical"],
    status: "active",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const mockUsers = [
  { id: "1", name: "John Smith", role: "engineer" },
  { id: "2", name: "Sarah Johnson", role: "engineer" },
  { id: "3", name: "Michael Chen", role: "engineer" },
  { id: "4", name: "Emily Davis", role: "manager" },
  { id: "5", name: "Current User", role: "engineer" },
];

export const mockTemplates = [
  {
    id: "1",
    name: "Planned Maintenance",
    description: "Scheduled planned maintenance for charging stations",
    steps: [
      {
        id: "step1",
        name: "Pre-Maintenance Check",
        description: "Initial verification and preparation",
        order: 1,
        fields: [
          { id: "field1", name: "Face Recognition", type: "faceRecognition", required: true },
          { id: "field2", name: "Site Location Check", type: "location", required: true },
          { id: "field3", name: "Arrival Photo", type: "photo", required: true },
          { id: "field4", name: "Equipment ID Verification", type: "text", required: true },
        ],
      },
      {
        id: "step2",
        name: "Physical Inspection",
        description: "Inspect physical condition of equipment",
        order: 2,
        fields: [
          { id: "field5", name: "Charging Cable Condition", type: "text", required: true },
          { id: "field6", name: "Display Screen Status", type: "text", required: true },
          { id: "field7", name: "Connector Port Inspection", type: "text", required: true },
          { id: "field8", name: "Enclosure Condition", type: "text", required: true },
          { id: "field9", name: "Inspection Photo", type: "photo", required: true },
        ],
      },
      {
        id: "step3",
        name: "Electrical Testing",
        description: "Perform electrical and functional tests",
        order: 3,
        fields: [
          { id: "field10", name: "Output Voltage (V)", type: "number", required: true },
          { id: "field11", name: "Current Rating (A)", type: "number", required: true },
          { id: "field12", name: "Ground Resistance", type: "text", required: true },
          { id: "field13", name: "GFCI Test Result", type: "text", required: true },
        ],
      },
      {
        id: "step4",
        name: "Software & Network Check",
        description: "Verify software and connectivity",
        order: 4,
        fields: [
          { id: "field14", name: "Software Version", type: "text", required: true },
          { id: "field15", name: "Network Connectivity", type: "text", required: true },
          { id: "field16", name: "Payment System Test", type: "text", required: true },
        ],
      },
      {
        id: "step5",
        name: "Completion & Sign-off",
        description: "Finalize maintenance work",
        order: 5,
        fields: [
          { id: "field17", name: "Overall Status", type: "text", required: true },
          { id: "field18", name: "Maintenance Notes", type: "text", required: false },
          { id: "field19", name: "Completion Photo", type: "photo", required: true },
          { id: "field20", name: "Technician Signature", type: "signature", required: true },
          { id: "field21", name: "Completion Time", type: "date", required: true },
        ],
      },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Preventive Maintenance",
    description: "Regular preventive maintenance to avoid failures",
    steps: [
      {
        id: "step1",
        name: "Arrival Verification",
        description: "Verify arrival at maintenance site",
        order: 1,
        fields: [
          { id: "field1", name: "Face Recognition", type: "faceRecognition", required: true },
          { id: "field2", name: "Location Check", type: "location", required: true },
          { id: "field3", name: "Equipment ID", type: "text", required: true },
        ],
      },
      {
        id: "step2",
        name: "Cleaning & Lubrication",
        description: "Clean and lubricate components",
        order: 2,
        fields: [
          { id: "field4", name: "Exterior Cleaning Status", type: "text", required: true },
          { id: "field5", name: "Connector Cleaning", type: "text", required: true },
          { id: "field6", name: "Ventilation Cleaning", type: "text", required: true },
          { id: "field7", name: "Before Cleaning Photo", type: "photo", required: true },
          { id: "field8", name: "After Cleaning Photo", type: "photo", required: true },
        ],
      },
      {
        id: "step3",
        name: "Component Inspection",
        description: "Inspect all major components",
        order: 3,
        fields: [
          { id: "field9", name: "Cable Wear Assessment", type: "text", required: true },
          { id: "field10", name: "Connector Wear Level", type: "text", required: true },
          { id: "field11", name: "Screen Functionality", type: "text", required: true },
          { id: "field12", name: "Cooling System Check", type: "text", required: true },
        ],
      },
      {
        id: "step4",
        name: "Safety Checks",
        description: "Perform safety inspections",
        order: 4,
        fields: [
          { id: "field13", name: "Emergency Stop Test", type: "text", required: true },
          { id: "field14", name: "Ground Connection", type: "text", required: true },
          { id: "field15", name: "Safety Labels Check", type: "text", required: true },
          { id: "field16", name: "Enclosure Integrity", type: "text", required: true },
        ],
      },
      {
        id: "step5",
        name: "Documentation",
        description: "Complete maintenance documentation",
        order: 5,
        fields: [
          { id: "field17", name: "Issues Found", type: "text", required: false },
          { id: "field18", name: "Recommendations", type: "text", required: false },
          { id: "field19", name: "Next Maintenance Date", type: "date", required: true },
          { id: "field20", name: "Technician Signature", type: "signature", required: true },
        ],
      },
    ],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "Corrective Maintenance",
    description: "Corrective maintenance for reported issues and failures",
    steps: [
      {
        id: "step1",
        name: "Issue Documentation",
        description: "Document the reported issue",
        order: 1,
        fields: [
          { id: "field1", name: "Face Recognition", type: "faceRecognition", required: true },
          { id: "field2", name: "Fault Location", type: "location", required: true },
          { id: "field3", name: "Issue Photo", type: "photo", required: true },
          { id: "field4", name: "Fault Description", type: "text", required: true },
          { id: "field5", name: "Error Codes", type: "text", required: false },
        ],
      },
      {
        id: "step2",
        name: "Diagnosis",
        description: "Diagnose the problem",
        order: 2,
        fields: [
          { id: "field6", name: "Root Cause Analysis", type: "text", required: true },
          { id: "field7", name: "Failed Component", type: "text", required: true },
          { id: "field8", name: "Diagnostic Test Results", type: "text", required: true },
          { id: "field9", name: "Diagnostic Photo", type: "photo", required: false },
        ],
      },
      {
        id: "step3",
        name: "Repair Work",
        description: "Perform corrective repairs",
        order: 3,
        fields: [
          { id: "field10", name: "Parts Replaced", type: "text", required: true },
          { id: "field11", name: "Part Serial Numbers", type: "text", required: false },
          { id: "field12", name: "Repair Procedure", type: "text", required: true },
          { id: "field13", name: "During Repair Photo", type: "photo", required: true },
        ],
      },
      {
        id: "step4",
        name: "Testing & Verification",
        description: "Test the repaired equipment",
        order: 4,
        fields: [
          { id: "field14", name: "Functional Test Result", type: "text", required: true },
          { id: "field15", name: "Charging Test (kW)", type: "number", required: true },
          { id: "field16", name: "Safety Test Result", type: "text", required: true },
          { id: "field17", name: "After Repair Photo", type: "photo", required: true },
        ],
      },
      {
        id: "step5",
        name: "Completion",
        description: "Complete corrective maintenance",
        order: 5,
        fields: [
          { id: "field18", name: "Equipment Status", type: "text", required: true },
          { id: "field19", name: "Downtime Duration (hours)", type: "number", required: true },
          { id: "field20", name: "Warranty Information", type: "text", required: false },
          { id: "field21", name: "Follow-up Required", type: "text", required: false },
          { id: "field22", name: "Technician Signature", type: "signature", required: true },
          { id: "field23", name: "Completion Time", type: "date", required: true },
        ],
      },
    ],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
];

export const mockSites = [
  {
    id: "S001",
    name: "Central Plaza",
    address: "123 Main Street, Bangkok, Thailand",
    level: "vip",
    status: "online",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "S002",
    name: "Shopping Mall B",
    address: "456 Shopping Avenue, Bangkok, Thailand",
    level: "normal",
    status: "online",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "S003",
    name: "Office Complex C",
    address: "789 Business Road, Bangkok, Thailand",
    level: "vip",
    status: "online",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "S004",
    name: "Highway Service Area D",
    address: "Highway 1, Km 50, Nakhon Pathom, Thailand",
    level: "normal",
    status: "online",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "S005",
    name: "Airport Terminal E",
    address: "Suvarnabhumi Airport, Samut Prakan, Thailand",
    level: "vip",
    status: "online",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "S006",
    name: "Hotel F",
    address: "321 Hotel Street, Bangkok, Thailand",
    level: "vip",
    status: "offline",
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-10-01"),
  },
  {
    id: "S007",
    name: "Residential Complex G",
    address: "654 Residential Lane, Bangkok, Thailand",
    level: "normal",
    status: "online",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "S008",
    name: "Industrial Park H",
    address: "987 Industrial Zone, Pathum Thani, Thailand",
    level: "normal",
    status: "underConstruction",
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-10-15"),
  },
];

export const mockTickets = [
  {
    id: "T001",
    title: "Monthly Inspection - Central Plaza",
    description: "Scheduled monthly inspection for Central Plaza charging stations",
    templateId: "1",
    templateName: "Planned Maintenance",
    type: "planned",
    site: "Central Plaza",
    status: "open",
    priority: "P2",
    assignedTo: "1",
    assignedToName: "John Smith",
    createdBy: "5",
    createdByName: "Current User",
    createdAt: new Date("2025-01-20"),
    dueDate: new Date("2025-01-25"),
    completedSteps: [],
    stepData: {},
    accepted: false,
    comments: [],
  },
  {
    id: "T002",
    title: "Routine Cleaning - Shopping Mall B",
    description: "Preventive maintenance and cleaning for Shopping Mall B stations",
    templateId: "2",
    templateName: "Preventive Maintenance",
    type: "preventive",
    site: "Shopping Mall B",
    status: "accepted",
    priority: "P3",
    assignedTo: "2",
    assignedToName: "Sarah Johnson",
    createdBy: "5",
    createdByName: "Current User",
    createdAt: new Date("2025-01-18"),
    dueDate: new Date("2025-01-22"),
    completedSteps: ["step1"],
    stepData: {},
    accepted: true,
    acceptedAt: new Date("2025-01-19"),
    comments: [
      {
        id: "c1",
        userId: "2",
        userName: "Sarah Johnson",
        comment: "Accepted. Will start tomorrow morning.",
        createdAt: new Date("2025-01-19"),
        type: "accept",
      },
    ],
  },
  {
    id: "T003",
    title: "Emergency Repair - Airport Terminal E",
    description: "Charging station not working, urgent repair needed",
    templateId: "3",
    templateName: "Corrective Maintenance",
    type: "corrective",
    site: "Airport Terminal E",
    status: "inProgress",
    priority: "P1",
    assignedTo: "3",
    assignedToName: "Michael Chen",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-01-21"),
    dueDate: new Date("2025-01-21"),
    completedSteps: ["step1", "step2"],
    stepData: {},
    accepted: true,
    acceptedAt: new Date("2025-01-21"),
    departureAt: new Date("2025-01-21T08:30:00"),
    arrivalAt: new Date("2025-01-21T09:15:00"),
    comments: [
      {
        id: "c2",
        userId: "3",
        userName: "Michael Chen",
        comment: "On my way to the site now.",
        createdAt: new Date("2025-01-21T08:30:00"),
        type: "general",
      },
    ],
  },
  {
    id: "T004",
    title: "Quarterly Inspection - Office Complex C",
    description: "Q1 2025 scheduled inspection",
    templateId: "1",
    templateName: "Planned Maintenance",
    type: "planned",
    site: "Office Complex C",
    status: "closed",
    priority: "P2",
    assignedTo: "1",
    assignedToName: "John Smith",
    createdBy: "5",
    createdByName: "Current User",
    createdAt: new Date("2025-01-10"),
    dueDate: new Date("2025-01-15"),
    completedSteps: ["step1", "step2", "step3", "step4", "step5"],
    stepData: {},
    accepted: true,
    acceptedAt: new Date("2025-01-11"),
    departureAt: new Date("2025-01-12T09:00:00"),
    arrivalAt: new Date("2025-01-12T09:45:00"),
    cause: "Regular maintenance completed. All systems functioning normally.",
    solution: "Cleaned connectors, tested all electrical systems, updated software to v2.5.1",
    comments: [],
  },
  {
    id: "T005",
    title: "Cable Replacement - Hotel F",
    description: "Damaged charging cable needs replacement",
    templateId: "3",
    templateName: "Corrective Maintenance",
    type: "corrective",
    site: "Hotel F",
    status: "onHold",
    priority: "P2",
    assignedTo: "2",
    assignedToName: "Sarah Johnson",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-01-19"),
    dueDate: new Date("2025-01-24"),
    completedSteps: ["step1"],
    stepData: {},
    accepted: true,
    acceptedAt: new Date("2025-01-20"),
    departureAt: new Date("2025-01-20T10:00:00"),
    arrivalAt: new Date("2025-01-20T10:40:00"),
    comments: [
      {
        id: "c3",
        userId: "2",
        userName: "Sarah Johnson",
        comment: "Waiting for replacement cable to arrive. ETA 2 days.",
        createdAt: new Date("2025-01-20"),
        type: "general",
      },
    ],
  },
];
