import {User, Template, Ticket, TicketStatus, Group, SLAConfig, ProblemType, SiteLevelConfig} from "./types";

export const mockGroups: Group[] = [
    {
        id: "g1",
        name: "Bangkok Maintenance Team",
        description: "Primary maintenance team for Bangkok region",
        tags: ["Bangkok", "Maintenance", "Primary"],
        status: "active",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
    },
    {
        id: "g2",
        name: "Support Team",
        description: "Remote support and troubleshooting team",
        tags: ["Support", "Remote", "L1"],
        status: "active",
        createdAt: new Date("2024-01-05"),
        updatedAt: new Date("2024-01-05"),
    },
];

export const mockUsers: User[] = [
    {
        id: "1",
        name: "John Smith",
        username: "johnsmith",
        role: "engineer",
        groupId: "g1",
        groupName: "Bangkok Maintenance Team",
        status: "active",
        createdAt: new Date("2024-01-01")
    },
    {
        id: "2",
        name: "Sarah Johnson",
        username: "sarahj",
        role: "engineer",
        groupId: "g1",
        groupName: "Bangkok Maintenance Team",
        status: "active",
        createdAt: new Date("2024-01-02")
    },
    {
        id: "3",
        name: "Michael Chen",
        username: "michaelc",
        role: "engineer",
        groupId: "g2",
        groupName: "Support Team",
        status: "active",
        createdAt: new Date("2024-01-03")
    },
    {
        id: "4",
        name: "Emily Davis",
        username: "emilyd",
        role: "manager",
        groupId: "g2",
        groupName: "Support Team",
        status: "active",
        createdAt: new Date("2024-01-01")
    },
    {
        id: "5",
        name: "Current User",
        username: "currentuser",
        role: "engineer",
        groupId: "g1",
        groupName: "Bangkok Maintenance Team",
        status: "active",
        createdAt: new Date("2024-01-01")
    },
];

export const mockTemplates: Template[] = [
    {
        id: "1",
        name: "Planned Maintenance",
        description: "Scheduled planned maintenance for charging stations",
        steps: [
            {
                id: "step1",
                name: "Pre-Maintenance Check",
                description: "Initial verification and preparation",
                order: 1,
                fields: [
                    {id: "field1", name: "Face Recognition", type: "faceRecognition", required: true},
                    {id: "field2", name: "Site Location Check", type: "location", required: true},
                    {id: "field3", name: "Arrival Photo", type: "photo", required: true},
                    {id: "field4", name: "Equipment ID Verification", type: "text", required: true},
                ],
            },
            {
                id: "step2",
                name: "Physical Inspection",
                description: "Inspect physical condition of equipment",
                order: 2,
                fields: [
                    {id: "field5", name: "Charging Cable Condition", type: "text", required: true},
                    {id: "field6", name: "Display Screen Status", type: "text", required: true},
                    {id: "field7", name: "Connector Port Inspection", type: "text", required: true},
                    {id: "field8", name: "Enclosure Condition", type: "text", required: true},
                    {id: "field9", name: "Inspection Photo", type: "photo", required: true},
                ],
            },
            {
                id: "step3",
                name: "Electrical Testing",
                description: "Perform electrical and functional tests",
                order: 3,
                fields: [
                    {id: "field10", name: "Output Voltage (V)", type: "number", required: true},
                    {id: "field11", name: "Current Rating (A)", type: "number", required: true},
                    {id: "field12", name: "Ground Resistance", type: "text", required: true},
                    {id: "field13", name: "GFCI Test Result", type: "text", required: true},
                ],
            },
            {
                id: "step4",
                name: "Software & Network Check",
                description: "Verify software and connectivity",
                order: 4,
                fields: [
                    {id: "field14", name: "Software Version", type: "text", required: true},
                    {id: "field15", name: "Network Connectivity", type: "text", required: true},
                    {id: "field16", name: "Payment System Test", type: "text", required: true},
                ],
            },
            {
                id: "step5",
                name: "Completion & Sign-off",
                description: "Finalize maintenance work",
                order: 5,
                fields: [
                    {id: "field17", name: "Overall Status", type: "text", required: true},
                    {id: "field18", name: "Maintenance Notes", type: "text", required: false},
                    {id: "field19", name: "Completion Photo", type: "photo", required: true},
                    {id: "field20", name: "Technician Signature", type: "signature", required: true},
                    {id: "field21", name: "Completion Time", type: "date", required: true},
                ],
            },
        ],
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "2",
        name: "Preventive Maintenance",
        description: "Regular preventive maintenance to avoid failures",
        steps: [
            {
                id: "step1",
                name: "Cabinet Inspection",
                description: "Check the MDB cabinet and charging station cabinet for rust, leaks, and the condition of the door handles.",
                order: 1,
                fields: [
                    {id: "field1_1", name: "Cabinet Condition", type: "text", required: true},
                    {id: "field1_2", name: "Cabinet Photo", type: "photo", required: true},
                ],
            },
            {
                id: "step2",
                name: "Fire Safety Check",
                description: "Check the fire extinguishers and monitor the equipment to ensure they are functioning properly.",
                order: 2,
                fields: [
                    {id: "field2_1", name: "Fire Extinguisher Status", type: "text", required: true},
                ],
            },
            {
                id: "step3",
                name: "Ground & Drainage",
                description: "Check the ground condition, drainage, and cleaning.",
                order: 3,
                fields: [
                    {id: "field3_1", name: "Ground Condition", type: "text", required: true},
                    {id: "field3_2", name: "Site Photo", type: "photo", required: false},
                ],
            },
            {
                id: "step4",
                name: "Cable & Gun Head",
                description: "Check the charging gun head and charging cable for any damage or scratches. Ensure the cable ends are securely installed.",
                order: 4,
                fields: [
                    {id: "field4_1", name: "Cable Condition", type: "text", required: true},
                    {id: "field4_2", name: "Gun Head Condition", type: "text", required: true},
                    {id: "field4_3", name: "Cable Photo", type: "photo", required: true},
                ],
            },
            {
                id: "step5",
                name: "Input Line Check",
                description: "Check if the charging input line is normal.",
                order: 5,
                fields: [
                    {id: "field5_1", name: "Input Line Status", type: "text", required: true},
                ],
            },
            {
                id: "step6",
                name: "Terminals & Cables",
                description: "Check that all terminals on the charging station's mainboard are securely plugged in and ensure all cables are secure.",
                order: 6,
                fields: [
                    {id: "field6_1", name: "Terminals Status", type: "text", required: true},
                    {id: "field6_2", name: "Internal Photo", type: "photo", required: true},
                ],
            },
            {
                id: "step7",
                name: "Display & Settings",
                description: "Check if the display screen is intact and verify that all parameter settings are correct.",
                order: 7,
                fields: [
                    {id: "field7_1", name: "Display Condition", type: "text", required: true},
                    {id: "field7_2", name: "Settings Verification", type: "text", required: true},
                ],
            },
            {
                id: "step8",
                name: "Indicator Lights",
                description: "Check if the indicator lights on the charging station are functioning properly.",
                order: 8,
                fields: [
                    {id: "field8_1", name: "Indicators Status", type: "text", required: true},
                ],
            },
            {
                id: "step9",
                name: "Communication Functions",
                description: "Check if all communication functions of the charging station are normal.",
                order: 9,
                fields: [
                    {id: "field9_1", name: "Comm Function Status", type: "text", required: true},
                ],
            },
            {
                id: "step10",
                name: "Emergency Stop",
                description: "Check that the emergency stop button is intact and that it functions properly.",
                order: 10,
                fields: [
                    {id: "field10_1", name: "E-Stop Condition", type: "text", required: true},
                    {id: "field10_2", name: "E-Stop Test Result", type: "text", required: true},
                ],
            },
            {
                id: "step11",
                name: "Charging Module",
                description: "Check if the charging module is operating normally and if the power indicator light is flashing. There should be no red alarm light illuminated.",
                order: 11,
                fields: [
                    {id: "field11_1", name: "Module Status", type: "text", required: true},
                    {id: "field11_2", name: "Alarm Light Check", type: "text", required: true},
                ],
            },
            {
                id: "step12",
                name: "Surge Protector",
                description: "Check that the surge protector is in good working order and has not been damaged.",
                order: 12,
                fields: [
                    {id: "field12_1", name: "Surge Protector Status", type: "text", required: true},
                ],
            },
            {
                id: "step13",
                name: "Dust Screen",
                description: "Check if the dust screen needs cleaning.",
                order: 13,
                fields: [
                    {id: "field13_1", name: "Cleaning Status", type: "text", required: true},
                    {id: "field13_2", name: "Photo Before/After", type: "photo", required: false},
                ],
            },
            {
                id: "step14",
                name: "Historical Records",
                description: "Check all historical records of the charging station for any abnormal fault data.",
                order: 14,
                fields: [
                    {id: "field14_1", name: "Fault Data Check", type: "text", required: true},
                ],
            },
            {
                id: "step15",
                name: "Backend Communication",
                description: "Check if the communication between the charging station and the backend is normal and if the data is being sent normally.",
                order: 15,
                fields: [
                    {id: "field15_1", name: "Backend Comm Status", type: "text", required: true},
                ],
            },
            {
                id: "step16",
                name: "Contactor & Charging Test",
                description: "Check if the charger contactor is functioning properly and On-site test of charging action.",
                order: 16,
                fields: [
                    {id: "field16_1", name: "Contactor Status", type: "text", required: true},
                    {id: "field16_2", name: "Charging Test Result", type: "text", required: true},
                ],
            },
        ],
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2025-12-04"),
    },
    {
        id: "3",
        name: "Corrective Maintenance",
        description: "Corrective maintenance for reported issues and failures",
        steps: [
            {
                id: "step1",
                name: "Issue Documentation",
                description: "Document the reported issue",
                order: 1,
                fields: [
                    {id: "field1", name: "Face Recognition", type: "faceRecognition", required: true},
                    {id: "field2", name: "Fault Location", type: "location", required: true},
                    {id: "field3", name: "Issue Photo", type: "photo", required: true},
                    {id: "field4", name: "Fault Description", type: "text", required: true},
                    {id: "field5", name: "Error Codes", type: "text", required: false},
                ],
            },
            {
                id: "step2",
                name: "Diagnosis",
                description: "Diagnose the problem",
                order: 2,
                fields: [
                    {id: "field6", name: "Root Cause Analysis", type: "text", required: true},
                    {id: "field7", name: "Failed Component", type: "text", required: true},
                    {id: "field8", name: "Diagnostic Test Results", type: "text", required: true},
                    {id: "field9", name: "Diagnostic Photo", type: "photo", required: false},
                ],
            },
            {
                id: "step3",
                name: "Repair Work",
                description: "Perform corrective repairs",
                order: 3,
                fields: [
                    {id: "field10", name: "Parts Replaced", type: "text", required: true},
                    {id: "field11", name: "Part Serial Numbers", type: "text", required: false},
                    {id: "field12", name: "Repair Procedure", type: "text", required: true},
                    {id: "field13", name: "During Repair Photo", type: "photo", required: true},
                ],
            },
            {
                id: "step4",
                name: "Testing & Verification",
                description: "Test the repaired equipment",
                order: 4,
                fields: [
                    {id: "field14", name: "Functional Test Result", type: "text", required: true},
                    {id: "field15", name: "Charging Test (kW)", type: "number", required: true},
                    {id: "field16", name: "Safety Test Result", type: "text", required: true},
                    {id: "field17", name: "After Repair Photo", type: "photo", required: true},
                ],
            },
            {
                id: "step5",
                name: "Completion",
                description: "Complete corrective maintenance",
                order: 5,
                fields: [
                    {id: "field18", name: "Equipment Status", type: "text", required: true},
                    {id: "field19", name: "Downtime Duration (hours)", type: "number", required: true},
                    {id: "field20", name: "Warranty Information", type: "text", required: false},
                    {id: "field21", name: "Follow-up Required", type: "text", required: false},
                    {id: "field22", name: "Technician Signature", type: "signature", required: true},
                    {id: "field23", name: "Completion Time", type: "date", required: true},
                ],
            },
        ],
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-01-10"),
    },
    {
        id: "4",
        name: "Problem Management Standard",
        description: "Standard template for problem management tickets",
        steps: [
            {
                id: "step1",
                name: "Problem Resolution",
                description: "Provide solution and evidence",
                order: 1,
                fields: [
                    {id: "field1", name: "Proposed Solution", type: "text", required: true},
                    {id: "field2", name: "Estimated Resolution Time", type: "text", required: true},
                    {id: "field3", name: "Evidence", type: "photo", required: true},
                ],
            },
        ],
        createdAt: new Date("2024-02-01"),
        updatedAt: new Date("2024-02-01"),
    },
];

export const mockSites = [
    {
        id: "S001",
        name: "Central Plaza",
        address: "123 Main Street, Bangkok, Thailand",
        level: "vip" as const,
        status: "online" as const,
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "S002",
        name: "Shopping Mall B",
        address: "456 Shopping Avenue, Bangkok, Thailand",
        level: "normal" as const,
        status: "online" as const,
        createdAt: new Date("2024-02-10"),
        updatedAt: new Date("2024-02-10"),
    },
    {
        id: "S003",
        name: "Office Complex C",
        address: "789 Business Road, Bangkok, Thailand",
        level: "vip" as const,
        status: "online" as const,
        createdAt: new Date("2024-01-20"),
        updatedAt: new Date("2024-01-20"),
    },
    {
        id: "S004",
        name: "Highway Service Area D",
        address: "Highway 1, Km 50, Nakhon Pathom, Thailand",
        level: "normal" as const,
        status: "online" as const,
        createdAt: new Date("2024-03-01"),
        updatedAt: new Date("2024-03-01"),
    },
    {
        id: "S005",
        name: "Airport Terminal E",
        address: "Suvarnabhumi Airport, Samut Prakan, Thailand",
        level: "vip" as const,
        status: "online" as const,
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-01-10"),
    },
    {
        id: "S006",
        name: "Hotel F",
        address: "321 Hotel Street, Bangkok, Thailand",
        level: "vip" as const,
        status: "offline" as const,
        createdAt: new Date("2024-04-05"),
        updatedAt: new Date("2024-10-01"),
    },
    {
        id: "S007",
        name: "Residential Complex G",
        address: "654 Residential Lane, Bangkok, Thailand",
        level: "normal" as const,
        status: "online" as const,
        createdAt: new Date("2024-02-15"),
        updatedAt: new Date("2024-02-15"),
    },
    {
        id: "S008",
        name: "Industrial Park H",
        address: "987 Industrial Zone, Pathum Thani, Thailand",
        level: "normal" as const,
        status: "underConstruction" as const,
        createdAt: new Date("2024-09-01"),
        updatedAt: new Date("2024-10-15"),
    },
];

export const mockTickets: Ticket[] = [
    {
        id: "T001",
        title: "Monthly Inspection - Central Plaza",
        description: "Scheduled monthly inspection for Central Plaza charging stations",
        templateId: "1",
        templateName: "Planned Maintenance",
        type: "planned",
        siteId: "S001",
        siteName: "Central Plaza",
        status: "open",
        priority: "P2",
        assignedTo: "1",
        assignedToName: "John Smith",
        createdBy: "5",
        createdByName: "Current User",
        createdAt: "2025-01-20 10:00:00",
        dueDate: "2025-01-25 18:00:00",
        completedSteps: [],
        stepData: {},
        accepted: false,
        comments: [],
        updatedAt: ""
    },
    {
        id: "T002",
        title: "Routine Cleaning - Shopping Mall B",
        description: "Preventive maintenance and cleaning for Shopping Mall B stations",
        templateId: "2",
        templateName: "Preventive Maintenance",
        type: "preventive",
        siteId: "S002",
        siteName: "Shopping Mall B",
        status: "accepted",
        priority: "P3",
        assignedTo: "2",
        assignedToName: "Sarah Johnson",
        createdBy: "5",
        createdByName: "Current User",
        createdAt: "2025-01-18 09:30:00",
        dueDate: "2025-01-22 17:00:00",
        completedSteps: ["step1"],
        stepData: {},
        accepted: true,
        acceptedAt: "2025-01-19 14:00:00",
        comments: [
            {
                id: "c1",
                userId: "2",
                userName: "Sarah Johnson",
                comment: "Accepted. Will start tomorrow morning.",
                createdAt: "2025-01-19 14:00:00",
                type: "ACCEPT",
            },
        ],
    },
    {
        id: "T003",
        title: "Emergency Repair - Airport Terminal E",
        description: "Charging station not working, urgent repair needed",
        templateId: "3",
        templateName: "Corrective Maintenance",
        type: "CORRECTIVE",
        siteId: "S005",
        siteName: "Airport Terminal E",
        status: "IN_PROGRESS",
        priority: "P1",
        assignedTo: "3",
        assignedToName: "Michael Chen",
        createdBy: "4",
        createdByName: "Emily Davis",
        createdAt: "2025-01-21 08:00:00",
        dueDate: "2025-01-21 16:00:00",
        completedSteps: ["step1", "step2"],
        stepData: {},
        accepted: true,
        acceptedAt: "2025-01-21 08:15:00",
        departureAt: "2025-01-21 08:30:00",
        arrivalAt: "2025-01-21 09:15:00",
        comments: [
            {
                id: "c2",
                userId: "3",
                userName: "Michael Chen",
                comment: "On my way to the site now.",
                createdAt: "2025-01-21 08:30:00",
                type: "GENERAL",
            },
        ],
    },
    {
        id: "T004",
        title: "Quarterly Inspection - Office Complex C",
        description: "Q1 2025 scheduled inspection",
        templateId: "1",
        templateName: "Planned Maintenance",
        type: "planned",
        siteId: "S003",
        siteName: "Office Complex C",
        status: "completed",
        priority: "P2",
        assignedTo: "1",
        assignedToName: "John Smith",
        createdBy: "5",
        createdByName: "Current User",
        createdAt: "2025-01-10 10:00:00",
        dueDate: "2025-01-15 18:00:00",
        completedSteps: ["step1", "step2", "step3", "step4", "step5"],
        stepData: {},
        accepted: true,
        acceptedAt: "2025-01-11 09:00:00",
        departureAt: "2025-01-12 09:00:00",
        arrivalAt: "2025-01-12 09:45:00",
        cause: "Regular maintenance completed. All systems functioning normally.",
        solution: "Cleaned connectors, tested all electrical systems, updated software to v2.5.1",
        comments: [],
    },
    {
        id: "T005",
        title: "Cable Replacement - Hotel F",
        description: "Damaged charging cable needs replacement",
        templateId: "3",
        templateName: "Corrective Maintenance",
        type: "CORRECTIVE",
        siteId: "S006",
        siteName: "Hotel F",
        status: "ON_HOLD",
        priority: "P2",
        assignedTo: "2",
        assignedToName: "Sarah Johnson",
        createdBy: "4",
        createdByName: "Emily Davis",
        createdAt: "2025-01-19 11:00:00",
        dueDate: "2025-01-24 17:00:00",
        completedSteps: ["step1"],
        stepData: {},
        accepted: true,
        acceptedAt: "2025-01-20 10:00:00",
        departureAt: "2025-01-20 10:00:00",
        arrivalAt: "2025-01-20 10:40:00",
        comments: [
            {
                id: "c3",
                userId: "2",
                userName: "Sarah Johnson",
                comment: "Waiting for replacement cable to arrive. ETA 2 days.",
                createdAt: "2025-01-20 11:00:00",
                type: "GENERAL",
            },
        ],
    },
];

export const mockSLAConfigs: SLAConfig[] = [
    {id: "SC1", priority: "P1", responseTimeMinutes: 60, completionTimeHours: 4},
    {id: "SC2", priority: "P2", responseTimeMinutes: 120, completionTimeHours: 8},
    {id: "SC3", priority: "P3", responseTimeMinutes: 240, completionTimeHours: 16},
    {id: "SC4", priority: "P4", responseTimeMinutes: 480, completionTimeHours: 24},
];

export const mockProblemTypes: ProblemType[] = [
    {id: "PT1", name: "Hardware Failure", description: "Physical component malfunction"},
    {id: "PT2", name: "Software Issue", description: "Software or configuration problems"},
    {id: "PT3", name: "Network Issue", description: "Connectivity or communication problems"},
    {id: "PT4", name: "Power Issue", description: "Power supply or electrical problems"},
];

export const mockSiteLevelConfigs: SiteLevelConfig[] = [
    {id: "SL1", levelName: "VIP", description: "Very Important Sites", maxConcurrentTickets: 3, escalationTimeHours: 2},
    {id: "SL2", levelName: "Normal", description: "Standard Sites", maxConcurrentTickets: 5, escalationTimeHours: 4},
    {id: "SL3", levelName: "Low Priority", description: "Low Priority Sites", maxConcurrentTickets: 10, escalationTimeHours: 8},
    {id: "SL1", levelName: "VIP", description: "Very Important Sites", maxConcurrentTickets: 3, slaMultiplier: 2},
    {id: "SL2", levelName: "Normal", description: "Standard Sites", maxConcurrentTickets: 5, slaMultiplier: 1},
    {id: "SL1", levelName: "VIP", description: "Very Important Sites", maxConcurrentTickets: 3, slaMultiplier: 2},
    {id: "SL2", levelName: "Normal", description: "Standard Sites", maxConcurrentTickets: 5, slaMultiplier: 1},
    {id: "SL3", levelName: "Low Priority", description: "Low Priority Sites", maxConcurrentTickets: 10, slaMultiplier: 0.5},
    {id: "SL1", levelName: "VIP", description: "Very Important Sites", maxConcurrentTickets: 3, slaMultiplier: 2},
    {id: "SL2", levelName: "Normal", description: "Standard Sites", maxConcurrentTickets: 5, slaMultiplier: 1},
    {id: "SL3", levelName: "Low Priority", description: "Low Priority Sites", maxConcurrentTickets: 10, slaMultiplier: 0.5},
];
